/** Design system Escuela ZAO — Play CDN (sin compilación) */
tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#444651',
        'on-background': '#0b1c30',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#757682',
        'outline-variant': '#c5c5d3',
        'surface-tint': '#4059aa',
        primary: '#00236f',
        'on-primary': '#ffffff',
        'primary-container': '#1e3a8a',
        'on-primary-container': '#90a8ff',
        'inverse-primary': '#b6c4ff',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b6c4ff',
        'on-primary-fixed': '#00164e',
        'on-primary-fixed-variant': '#264191',
        secondary: '#785a00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdc425',
        'on-secondary-container': '#6d5200',
        'secondary-fixed': '#ffdf9a',
        'secondary-fixed-dim': '#f7be1d',
        'on-secondary-fixed': '#251a00',
        'on-secondary-fixed-variant': '#5a4300',
        tertiary: '#00311f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#004a31',
        'on-tertiary-container': '#27c38a',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        base: '8px',
        margin: '32px',
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 4px 24px -4px rgba(0, 35, 111, 0.1)',
        'card-hover': '0 12px 40px -12px rgba(0, 35, 111, 0.18)',
        header: '0 2px 16px rgba(0, 35, 111, 0.12)',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
};
